/**
 * Drizzle Agent Registry
 *
 * Implements AgentRegistry by querying the `agents` table.
 */

import { db } from './connection.js';
import { agents } from './schema.js';
import { eq, and, desc, type SQL } from 'drizzle-orm';
import type { AnyPgColumn } from 'drizzle-orm/pg-core';
import { withTenant, type Tx, type TenantContext } from './tenancy.js';
import type { AgentRegistry, AgentRegistryEntry, AgentRegistryInput } from '@cycgraph/orchestrator';

/** A query handle usable for both standalone (`db`) and tenant-scoped (`tx`) work. */
type Queryer = typeof db | Tx;

export interface DrizzleAgentRegistryOptions {
  /**
   * Tenant whose agents this registry sees. When set, reads/updates/deletes
   * are filtered to the tenant and registrations stamp `tenant_id`; agent
   * names are unique per tenant (see `uq_agents_tenant_name`). When omitted,
   * single-tenant (seed default) — the common global-registry case.
   */
  tenant?: TenantContext;
}

export class DrizzleAgentRegistry implements AgentRegistry {
  private readonly tenant?: TenantContext;

  constructor(options?: DrizzleAgentRegistryOptions) {
    this.tenant = options?.tenant;
  }

  private get tenantValues(): { tenant_id: string } | Record<string, never> {
    return this.tenant ? { tenant_id: this.tenant.tenant_id } : {};
  }

  private tenantEq(col: AnyPgColumn): SQL | undefined {
    return this.tenant ? eq(col, this.tenant.tenant_id) : undefined;
  }

  private read<T>(fn: (q: Queryer) => Promise<T>): Promise<T> {
    return this.tenant ? withTenant(this.tenant.tenant_id, fn) : fn(db);
  }

  async loadAgent(id: string): Promise<AgentRegistryEntry | null> {
    const result = await this.read((q) => q
      .select()
      .from(agents)
      .where(and(eq(agents.id, id), this.tenantEq(agents.tenant_id)))
      .limit(1));

    if (result.length === 0) return null;

    const row = result[0];
    return {
      id: row.id,
      name: row.name,
      description: row.description,
      model: row.model,
      provider: row.provider,
      system_prompt: row.system_prompt,
      temperature: row.temperature,
      max_steps: row.max_steps,
      tools: row.tools,
      permissions: row.permissions,
      ...(row.provider_options ? { provider_options: row.provider_options } : {}),
      ...(row.model_preference ? { model_preference: row.model_preference as 'high' | 'medium' | 'low' } : {}),
    };
  }

  /**
   * Register a new agent and return its auto-generated UUID.
   *
   * Satisfies the {@link AgentRegistry} interface contract.
   * The `id` is generated by Postgres via `defaultRandom()`.
   */
  async register(input: AgentRegistryInput): Promise<string> {
    return this.registerAgent(input);
  }

  /**
   * Register a new agent and return its auto-generated UUID.
   *
   * @deprecated Use {@link register} instead. Kept for backward compatibility.
   */
  async registerAgent(input: AgentRegistryInput): Promise<string> {
    const result = await this.read((q) => q
      .insert(agents)
      .values({
        ...this.tenantValues,
        name: input.name,
        description: input.description ?? null,
        model: input.model,
        provider: input.provider,
        system_prompt: input.system_prompt,
        temperature: input.temperature ?? 0.7,
        max_steps: input.max_steps ?? 10,
        tools: input.tools,
        permissions: {
          sandbox: input.permissions?.sandbox ?? false,
          read_keys: input.permissions?.read_keys ?? [],
          write_keys: input.permissions?.write_keys ?? [],
          ...(input.permissions?.budget_usd !== undefined ? { budget_usd: input.permissions.budget_usd } : {}),
        },
        ...(input.provider_options ? { provider_options: input.provider_options } : {}),
        ...(input.model_preference ? { model_preference: input.model_preference } : {}),
      })
      .returning({ id: agents.id }));

    return result[0].id;
  }

  /** Update an existing agent's configuration. */
  async updateAgent(id: string, updates: Partial<AgentRegistryInput>): Promise<void> {
    const set: Record<string, unknown> = { updated_at: new Date() };
    if (updates.name !== undefined) set.name = updates.name;
    if (updates.description !== undefined) set.description = updates.description;
    if (updates.model !== undefined) set.model = updates.model;
    if (updates.provider !== undefined) set.provider = updates.provider;
    if (updates.system_prompt !== undefined) set.system_prompt = updates.system_prompt;
    if (updates.temperature !== undefined) set.temperature = updates.temperature;
    if (updates.max_steps !== undefined) set.max_steps = updates.max_steps;
    if (updates.tools !== undefined) set.tools = updates.tools;
    if (updates.permissions !== undefined) set.permissions = updates.permissions;
    if (updates.provider_options !== undefined) set.provider_options = updates.provider_options;
    if (updates.model_preference !== undefined) set.model_preference = updates.model_preference;

    await this.read((q) => q.update(agents).set(set).where(and(eq(agents.id, id), this.tenantEq(agents.tenant_id))));
  }

  /** List registered agents with optional pagination. */
  async listAgents(opts: { limit?: number; offset?: number } = {}): Promise<AgentRegistryEntry[]> {
    const { limit = 100, offset = 0 } = opts;
    const rows = await this.read((q) => q
      .select()
      .from(agents)
      .where(this.tenantEq(agents.tenant_id))
      .orderBy(desc(agents.created_at))
      .limit(limit)
      .offset(offset));

    return rows.map(row => ({
      id: row.id,
      name: row.name,
      description: row.description,
      model: row.model,
      provider: row.provider,
      system_prompt: row.system_prompt,
      temperature: row.temperature,
      max_steps: row.max_steps,
      tools: row.tools,
      permissions: row.permissions,
      ...(row.provider_options ? { provider_options: row.provider_options } : {}),
      ...(row.model_preference ? { model_preference: row.model_preference as 'high' | 'medium' | 'low' } : {}),
    }));
  }

  /** Delete an agent by ID. Returns `true` if it existed. */
  async deleteAgent(id: string): Promise<boolean> {
    const result = await this.read((q) => q
      .delete(agents)
      .where(and(eq(agents.id, id), this.tenantEq(agents.tenant_id)))
      .returning({ id: agents.id }));
    return result.length > 0;
  }
}
